---
title: "Comparisons in the benchmark package"
author: "  "
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
---

# Sketch of comparison

```{r setup}
library(Benchmark)
m1 = micro_readVcf()
m2 = micro_getVariantCalls()
m3 = micro_getVariantCalls(datasetId="4252737135923902652" )
m1[[1]]
m2[[1]]
m3[[1]]
```
Harness is a program that runs other programs.
```{r doharn}
varHarness = function( ranges, methods, times=5 ) {
  lapply(ranges, function(range) {
     lapply( methods, function(f) f(range, times) )
     } )
  }
 cloudReadVcf = function(range, times) {
   chr = as.character(seqnames(range))
   start = start(range)
   end = end(range)
   micro_readVcf( chr=chr, start=start, end=end, times=times )
 }
 cloudMeth = micro_readVcf_clo(s3_1kg("17"))
 localMeth = micro_readVcf_clo(...local file...)
 methodList = list(cloud=cloudMeth, local=localMeth)
 varHarness( GRanges("17", IRanges(16.05e6, widths=c(100, 500, 1000, 5000))), methodList, times=2 )
 ```

